osx_image: xcode7.3

sudo: required
dist: trusty

language: node_js
node_js:
  - 'node'
  - '9'

matrix:
  include:
    - os: osx
      env: TRAVIS_NODE_VERSION="8"
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1 TRAVIS_NODE_VERSION="8"
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - rpm
      - bsdtar

cache:
  directories:
  - $HOME/.electron

install:
  - npm install -g npm
  - npm ci

before_script:
  - export TRAVIS=1
  - npm ci
  - npm run lint

script:
  - npm run build
  - npm test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+.*/"
