osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1 TRAVIS_NODE_VERSION="7.7.4"
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - rpm
      - bsdtar

cache:
  directories:
  - $HOME/.electron

install:
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use 7
  - npm install -g npm@latest
  - npm install --silent

before_script:
  - export TRAVIS=1
  - npm install --silent
  - npm run lint

script:
  - npm run build
  - npm test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+.*/"
