platform:
  - x64

cache:
  # - node_modules
  # - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm install --silent
  - npm run lint

test_script:
  - node --version
  - npm --version
  - npm test

build_script:
  - npm run build
  - .\node_modules\.bin\gulp build_plugins
  - cd .\dist\win-ia32-unpacked\resources\app\node_modules\
  - npm pack .\electron-vibrancy
  - cd ..\..\..\..\win-unpacked\resources\app\node_modules\
  - npm pack .\electron-vibrancy

artifacts:
  - path: dist\*.exe
    name: installer
  - path: dist\*.7z
    name: Archive
  - path: dist\*.7z
    name: Archive
  - path: dist\win-ia32-unpacked\resources\app\node_modules\electron-vibrancy*.tgz
    name: electron-vibrancy-prebuilt-ia32
  - path: dist\win-unpacked\resources\app\node_modules\electron-vibrancy*.tgz
    name: electron-vibrancy-prebuilt-x64

branches:
  except:
    - /^v\d+\.\d+\.\d+.*/
